#!/usr/bin/env bash

cd web

echo 'Installing npm modules inside web/ directory...'

npm i

echo 'Building project inside web/ directory...'

npm run build

echo 'Removing node_modules inside web/ directory...'

rm -rf node_modules

exit 0